name: awud_application
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_session: ^0.1.7
  rxdart: '^0.27.0'
  just_audio_mpv: ^0.1.4
  just_audio_windows: ^0.1.0
  just_audio: ^0.9.24
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  flutter_feather_icons: ^2.0.0+1
  google_nav_bar: ^5.0.6
  google_fonts: ^2.3.0
  flutter_spinkit: ^5.1.0
  mongo_dart: ^0.7.4+1
  dio: ^4.0.6
  http: ^0.13.4
  get: ^4.3.7
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  provider: ^6.0.3
  audioplayers: ^0.20.1
  audio_video_progress_bar: ^0.9.0
  share: ^2.0.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  path_provider: ^2.0.10
  google_sign_in: ^5.3.1
  sliding_sheet: ^0.5.2
  audio_service: ^0.18.4
  flutter_stripe: ^3.1.0
  cached_network_image: ^3.2.1
  # Other platform implementations below:
  # just_audio_libwinmedia: ^0.0.4
#  just_audio:
#    path: ../

# Uncomment when testing platform interface changes.
# dependency_overrides:
#   just_audio_platform_interface:
#     path: ../../just_audio_platform_interface
#   just_audio_web:
#     path: ../../just_audio_web

dev_dependencies:
  # TODO: uncomment these dependencies when they have nullsafe versions.
  # flutter_driver:
  #   sdk: flutter
  flutter_test:
    sdk: flutter
  # integration_test: ^1.0.1
  test: ^1.16.4
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - audio/
    - assets/images/
    - assets/audio/
    - lib/l10n/
    - assets/text/
